version = 0.1
[default.deploy.parameters]
stack_name = "sam-goserverless"
resolve_s3 = true
s3_prefix = "sam-goserverless"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TableName=\"GoServerlessTable\""
image_repositories = []
profile = "ddc-dev-ab"
