AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Serverless Go API - Amazon API Gateway to AWS Lambda to Amazon DynamoDB

Globals:
  Api:
    OpenApiVersion: 3.0.1
  Function:
    Timeout: 60
    MemorySize: 256

Parameters:
  ProjectName:
    Type: String
    Description: (Required) The name of the project
    MinLength: 3
    MaxLength: 50
    AllowedPattern: ^[A-Za-z_-]+$
    ConstraintDescription: "Required. Can be characters, hyphen, and underscore only. No numbers or special characters allowed."
  StageName:
    Type: String
    Default: dev
    Description: Enter dev, prod. Default is dev.
    AllowedValues:
      - dev
      - prod

Resources:
  UsersRestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "${ProjectName}_UsersAPI_${StageName}"
      StageName: !Ref StageName

  UsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ProjectName}_UsersCRUD_${StageName}"
      CodeUri: cmd/
      Handler: main
      Runtime: go1.x
      Architectures:
        - x86_64
      AutoPublishAlias: live
      DeploymentPreference:
        Type: AllAtOnce
      Policies:
        DynamoDBCrudPolicy:
          TableName: !Ref DynamoDBTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: ANY
            RestApiId: !Ref UsersRestApi
      Environment:
        Variables:
          DB_NAME: !Ref DynamoDBTable

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${ProjectName}_Table_${StageName}"
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  EndpointUrl:
    Description: "HTTP REST endpoint URL"
    Value: !Sub "https://${UsersRestApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/"

  LambdaFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt UsersFunction.Arn
